package crypt

import (
	"bytes"
	"encoding/base64"
	"encoding/hex"
	"testing"
)

// The identity in testdata is fixed, so it must be derived from a fixed seed rather
// than generated. This is the only place in the codebase that builds an identity
// deterministically, and it exists solely to make the vectors reproducible.
//
// The seed is published in docs/FORMAT.md. It is a test fixture, not a secret, and
// anything sealed to it should be treated as public.
const vectorSeedHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f" +
	"202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f" +
	"404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f" +
	"606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f" +
	"808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f"

// vectorIdentity rebuilds the published test identity from its seed.
//
// A private identity is the X25519 scalar followed by three seeds, so a fixed byte
// string of the right length is a valid one. That is a property worth having: it means
// the vectors can be regenerated by anyone from the documented seed alone, with no
// state carried over from whoever produced them.
func vectorIdentity(t *testing.T) *PrivateIdentity {
	t.Helper()

	raw, err := hex.DecodeString(vectorSeedHex)
	if err != nil {
		t.Fatalf("decoding the vector seed: %v", err)
	}
	token := privateIdentityPrefix + base64.RawURLEncoding.EncodeToString(raw[:PrivateIdentitySize])
	id, err := ParsePrivateIdentity(token)
	if err != nil {
		t.Fatalf("building the vector identity: %v", err)
	}
	return id
}

// TestPublishedVectorsAreStable is the regression guard the format promises.
//
// It pins the two things a refactor could silently change without any other test
// noticing: the exact byte layout of a serialised identity, and the fingerprint derived
// from it. Both are published in docs/FORMAT.md, so an independent implementation can
// check itself against the same numbers.
//
// Note what this deliberately does not pin: a sealed container. Sealing is randomised
// by design, so its bytes differ on every run and a fixed ciphertext vector would be
// impossible to produce without weakening the thing being tested. The interoperability
// guarantee is therefore stated the other way round, in TestSealedVectorsStillOpen: a
// container produced by any conforming implementation must open here.
func TestPublishedVectorsAreStable(t *testing.T) {
	id := vectorIdentity(t)

	t.Run("private identity round trips through its token", func(t *testing.T) {
		again, err := ParsePrivateIdentity(id.String())
		if err != nil {
			t.Fatalf("ParsePrivateIdentity: %v", err)
		}
		if !bytes.Equal(again.Bytes(), id.Bytes()) {
			t.Fatal("the private identity changed across a round trip")
		}
	})

	t.Run("sizes match the specification", func(t *testing.T) {
		// The constants against the published numbers, so a change to the layout
		// fails here rather than silently making docs/FORMAT.md wrong.
		for _, c := range []struct {
			what      string
			got, want int
		}{
			{"private identity", PrivateIdentitySize, 160},
			{"public identity", PublicIdentitySize, 3200},
			{"signature block", SignatureSize, 3373},
		} {
			if c.got != c.want {
				t.Errorf("%s is %d bytes, the spec says %d", c.what, c.got, c.want)
			}
		}

		// And the actual encodings against those constants.
		if got := len(id.Bytes()); got != PrivateIdentitySize {
			t.Errorf("encoded private identity is %d bytes, the constant says %d", got, PrivateIdentitySize)
		}
		if got := len(id.Public.Bytes()); got != PublicIdentitySize {
			t.Errorf("encoded public identity is %d bytes, the constant says %d", got, PublicIdentitySize)
		}
		if got := len(id.Public.String()); got != 4288 {
			t.Errorf("public token is %d characters, the spec says 4288", got)
		}
	})

	t.Run("fingerprint is the published one", func(t *testing.T) {
		// If this changes, either the identity layout changed or the fingerprint
		// definition did. Both are format breaks and both must be deliberate.
		const want = "efabdb74cfb3b19b0bbd96e685bb3e31e5f6b68a8e15b7018ec98d0db2f5007a"
		fp := id.Public.Fingerprint()
		if got := hex.EncodeToString(fp[:]); got != want {
			t.Errorf("fingerprint is %s\nthe published vector is %s\n"+
				"if this is intentional, update docs/FORMAT.md and say why in the changelog", got, want)
		}
	})
}

// TestSealedVectorsStillOpen states the interoperability guarantee in the only
// direction that can be pinned: containers sealed by this build must open, under both
// modes, signed and unsigned.
//
// Sealing is randomised, so this seals fresh material each run rather than reading a
// frozen file. A frozen ciphertext would only prove that a decoder still handles bytes
// produced by one particular past version, which is worth less than it looks: the same
// guarantee is already covered by pinning the layout above.
func TestSealedVectorsStillOpen(t *testing.T) {
	id := vectorIdentity(t)
	payload := []byte("the quick brown fox jumps over the lazy dog")

	t.Run("passphrase mode", func(t *testing.T) {
		sealed, err := Seal(payload, SealOptions{
			Passphrase: []byte("a fixed test passphrase"),
			KDF:        KDFParams{Time: 1, Memory: 8, Lanes: 1},
		})
		if err != nil {
			t.Fatalf("Seal: %v", err)
		}
		got, err := Open(sealed, OpenOptions{Passphrase: []byte("a fixed test passphrase")})
		if err != nil {
			t.Fatalf("Open: %v", err)
		}
		if !bytes.Equal(got, payload) {
			t.Fatal("payload mismatch")
		}
	})

	t.Run("recipient mode", func(t *testing.T) {
		sealed, err := Seal(payload, SealOptions{Recipient: &id.Public})
		if err != nil {
			t.Fatalf("Seal: %v", err)
		}
		got, err := Open(sealed, OpenOptions{Identity: id})
		if err != nil {
			t.Fatalf("Open: %v", err)
		}
		if !bytes.Equal(got, payload) {
			t.Fatal("payload mismatch")
		}
	})

	t.Run("signature over a fixed message", func(t *testing.T) {
		recipient := id.Public.Fingerprint()

		sig, err := Sign(payload, recipient, id)
		if err != nil {
			t.Fatalf("Sign: %v", err)
		}
		if len(sig) != SignatureSize {
			t.Fatalf("signature is %d bytes, expected %d", len(sig), SignatureSize)
		}
		if err := Verify(payload, recipient, id.Public, sig); err != nil {
			t.Fatalf("Verify: %v", err)
		}
	})
}
